Dylan/s3en 2278 implement trace search
Scale3-Labs/langtrace pull request #127
Opened 2024-05-31 00:28 UTC by dylanzuber-scale3

2024-06-07 00:32 UTC, karthikscale3 commented on components/project/traces/trace-filter.tsx
> +} from "@langtrase/trace-attributes";
this approach wouldn't work anymore cos these attributes have moved over to the typescript SDK now. So we need to import it from the typescript SDK instead. Install the latest version of trace attributes and you will see this break.

2024-06-07 00:33 UTC, karthikscale3 commented on components/project/traces/trace-filter.tsx
> +  const attributes = [
we should import these attributes from trace attributes, cos otherwise we will have to constantly maintain this list.

2024-06-07 00:34 UTC, karthikscale3 requested changes
so this PR needs two things:

1. functionality has bugs - needs to be fixed
2. UI is very rough, gotta polish it up quite a bit

2024-06-11 01:06 UTC, karthikscale3 commented
@ellipsis-dev review this

2024-06-11 15:04 UTC, rohit-kadhe approved these changes

2024-06-11 15:06 UTC, karthikscale3 approved these changes

2024-06-11 15:07 UTC, merged